#!/bin/sh

# immediately exit on any unhandled error
set -e

# current working directory
cwd=${0%/*}


#
# script entry function
#
cmd() {
  gawk -i inplace \
    'BEGIN { toc = 0; }
    /<!-- Table of Contents -->/ {
      toc = 1;
      print;
      system("gh-md-toc README.md");
    }
    /<!-- !Table of Contents -->/ { toc = 0; }
    toc == 0 { print; }' \
    README.md

  sed -i \
      -e 's/Created by \[gh-md-toc\]/Generated by [gh-md-toc]/g' \
      -e "s#\(https://cdn.rawgit.com/farjump/raspberry-pi/\)feature-readme-get-started/#\1$(git rev-parse --abbrev-ref HEAD)/#g" \
      README.md

  return 0
}

cmd $@
